name: Assign Issue
on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue comment
        uses: actions/github-script@v3
        with:
          script: |
            const issueComment = await github.issueComment.get({
              issue_id: context.issue.id,
              comment_id: context.payload.comment.id
            });
            const issue = context.issue.id
            const username = issueComment.body.match(/\/assign\s+(\S+)/)[1];
          
      - name: Assign issue
        uses: voxmachina/assign-issue-action@v1
        with:
          issue-id: ${{ inputs.issue_id }}
          assignee: ${{ steps.get-issue-comment.outputs.username }}
