name: Assign Issue
on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue comment
        uses: actions/github-script@v3
        with:
          script: |
            const issueComment =  github.event.comment.body
            const issue = context.issue.id
            const username = issueComment.body.match(/\/assign\s+(\S+)/)[1];
            
                        // Assign the issue to the username
            github.issues.update({
              issue_number: context.issue.id,
              assignees: username,
            });
        




          
          
          
